_core:
  default_config_hash: mxtw4e4xU9JhI4I-zBlL-b9NX0_QQ_ERLaKuPS2Am1A
langcode: en
display_denied_message: false
access_denied_message: 'Access denied. You must log in to view this page.'
access_denied_message_type: error
redirect_authenticated_users_to: ''
user_login_path: /saml_login
default_redirect_code: 302
destination_parameter_override: ReturnTo
match_noredirect_pages: ''
redirect_to_destination: true
throw_authenticated_404: false
