_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
module:
  acquia_connector: 0
  acquia_purge: 0
  action: 0
  address: 0
  addtocalendar: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  allowed_formats: 0
  anchor_link: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  ckwordcount: 0
  coffee: 0
  color: 0
  comment: 0
  conditional_fields: 0
  config: 0
  config_filter: 0
  config_log: 0
  config_split: 0
  config_update: 0
  consumers: 0
  contact: 0
  contextual: 0
  core_event_dispatcher: 0
  csv_serialization: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  datetime_range: 0
  draggableviews: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  entity_usage: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  fakeobjects: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filefield_paths: 0
  filter: 0
  flag: 0
  google_tag: 0
  graphql: 0
  graphql_core: 0
  graphql_views: 0
  help: 0
  history: 0
  hook_event_dispatcher: 0
  http_response_headers: 0
  image: 0
  inline_entity_form: 0
  insider_announcement: 0
  insider_comments: 0
  insider_featured: 0
  insider_forms: 0
  insider_gallery_slideshow: 0
  insider_headless: 0
  insider_interceptor: 0
  insider_linkit_alter: 0
  insider_masquerade: 0
  insider_media: 0
  insider_migration: 0
  insider_operating_procedure: 0
  insider_pages: 0
  insider_poll: 0
  insider_quicklinks: 0
  insider_scheduling_options: 0
  insider_solr_search: 0
  insider_view: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  jquery_ui_datepicker: 0
  jquery_ui_draggable: 0
  jquery_ui_droppable: 0
  jquery_ui_slider: 0
  jquery_ui_tabs: 0
  jquery_ui_touch_punch: 0
  language: 0
  layout_discovery: 0
  link: 0
  linkit: 0
  maillog: 0
  mailsystem: 0
  masquerade: 0
  media: 0
  media_entity_download: 0
  menu_ui: 0
  migrate: 0
  migrate_node_media: 0
  migrate_plus: 0
  migrate_tools: 0
  mysql: 0
  no_autocomplete: 0
  node: 0
  node_log: 0
  node_save_redirect: 0
  notification: 0
  options: 0
  other_view_filter: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  panelizer: 0
  panels: 0
  panels_ipe: 0
  paragraphs: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  poll: 0
  purge: 0
  purge_drush: 0
  purge_processor_cron: 0
  purge_processor_lateruntime: 0
  purge_queuer_coretags: 0
  purge_tokens: 0
  purge_ui: 0
  quickedit: 0
  quicktabs: 0
  quicktabs_jqueryui: 0
  rabbit_hole: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  replicate: 0
  replicate_actions: 0
  replicate_ui: 0
  rest: 0
  rh_media: 0
  rh_node: 0
  role_log: 0
  scheduled_updates: 0
  search: 0
  search_api: 0
  search_api_attachments: 0
  search_api_db: 0
  search_api_solr: 0
  sec_admin: 0
  sec_event: 0
  sec_roles_and_permissions: 0
  sec_twigextensions: 0
  sec_video: 0
  sec_view_filter_plugin: 0
  sec_workflow: 0
  serialization: 0
  shortcut: 0
  simple_oauth: 0
  simple_styleguide: 0
  single_datetime: 0
  subpathauto: 0
  swiftmailer: 0
  syslog: 0
  system: 0
  taxonomy: 0
  text: 0
  tippy_lib: 0
  token: 0
  token_filter: 0
  toolbar: 0
  tour: 0
  tracker: 0
  twig_tweak: 0
  update: 0
  user: 0
  video_embed_field: 0
  views_data_export: 0
  views_ifempty: 0
  views_natural_sort: 0
  views_ui: 0
  webform: 0
  webform_templates: 0
  webform_ui: 0
  workbench: 0
  workbench_access: 0
  workbench_moderation: 0
  workbench_moderation_actions: 0
  extlink: 1
  menu_link_content: 1
  pathauto: 1
  externalauth: 10
  views: 10
  publication_date: 99
  insider_general: 100
  comment_delete: 1000
  standard: 1000
theme:
  bartik: 0
  seven: 0
  adminimal_theme: 0
  insider: 0
profile: standard
