local_task_enabled_entity_types: {  }
track_enabled_source_entity_types:
  - block_content
  - comment
  - contact_message
  - media
  - node
  - paragraph
  - scheduled_update
  - search_api_task
  - shortcut
  - webform_submission
  - section_association
  - menu_link_content
track_enabled_target_entity_types:
  - block_content
  - comment
  - contact_message
  - media
  - node
  - paragraph
  - scheduled_update
  - search_api_task
  - shortcut
  - webform_submission
  - section_association
  - menu_link_content
track_enabled_plugins:
  - block_field
  - dynamic_entity_reference
  - entity_embed
  - entity_reference
  - html_link
  - link
  - linkit
track_enabled_base_fields: false
site_domains: {  }
edit_warning_message_entity_types: {  }
delete_warning_message_entity_types: {  }
usage_controller_items_per_page: 25
