_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: current
defaults:
  sender: maillog
  formatter: php_mail
modules:
  swiftmailer:
    none:
      sender: swiftmailer
      formatter: swiftmailer
  insider_comments:
    none:
      sender: maillog
      formatter: swiftmailer
