_core:
  default_config_hash: xUM87_G0_CpUtPj2V0GCZ849v_td1EjXWDQcRo8FGM4
extraction_method: solr_extractor
tika_extractor_configuration:
  java_path: ''
  tika_path: ''
tika_server_extractor_configuration:
  scheme: http
  host: localhost
  port: '9998'
  timeout: 5
docconv_extractor_configuration:
  docconv_path: /usr/bin/docd
solr_extractor_configuration:
  solr_server: acquia_search_server
python_pdf2txt_extractor_configuration:
  python_path: python
  python_pdf2txt_script: /usr/bin/pdf2txt.py
pdftotext_extractor_configuration:
  pdftotext_path: pdftotext
preserve_cache: true
read_text_files_directly: false
dependencies:
  module:
    - insider_solr_search
