<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Hook to restrict masquerade dropdown to 'enduser' account.
 */

function insider_featured_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id == 'views_form_highlights_page_1') {

    if (function_exists('draggableviews_views_submit')) { 

      $form['save_order'] = array(
        '#type' => 'submit',
        '#value' => t('Save order'),
        '#weight' => -1000,
        '#submit' => array('draggableviews_views_submit'),
        '#attributes' => array('class' => array('draggableviews-top-button')),
      );

    }

    return $form;
  }
}

function insider_featured_page_attachments(array &$page) {
	if (!\Drupal::service('router.admin_context')->isAdminRoute()) {
		return;
	}

	$page['#attached']['library'][] = 'insider_featured/insider_featured_admin';
}
