config_log.admin:
  path: 'admin/config/development/config_log'
  defaults:
    _form: '\Drupal\config_log\Form\ConfigLogConfigForm'
    _title: 'Configuration Log'
  requirements:
    _permission: 'administer site configuration'
